;
; FLASH BACKGROUND/BORDER
;
; 10 SYS (49152)

*=$0801

        BYTE    $0E, $08, $0A, $00, $9E, $20, $28,  $34, $39, $31, $35, $32, $29, $00, $00, $00


*=$C000
BORDER  = $D020 ; BORDER
BACK    = $D021 ; BACKGROUND
IRQROUT = $EA31
IRQVEC  = $314
;
NUMBER  = 30 ; EVERY HALF SECOND
;
INIT  SEI
      LDA #<BLINK
      LDY #>BLINK
      STA IRQVEC
      STY IRQVEC+1
      CLI
      RTS
;
BLINK DEC COUNT
      BNE DONE
      LDA #NUMBER
      STA COUNT ; RESET COUNTER
;
; EXCHANGE COLOURS
      LDX BACK
      LDA BORDER
      STA BACK
      STX BORDER
DONE  JMP IRQROUT
;
COUNT BYTE 30

